# Generated by Django 3.2.7 on 2021-09-17 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='date_created')),
                ('drink_type', models.PositiveSmallIntegerField(choices=[(0, 'Beer'), (1, 'Wine'), (2, 'Cider'), (3, 'Vodka'), (4, 'Gin'), (5, 'Whiskey'), (6, 'Rum'), (7, 'Tequila'), (8, 'Brandy'), (9, 'Bitters'), (10, 'Alcopops'), (11, 'Absinthe'), (12, 'Amaretto'), (13, 'Aperol'), (14, 'Averna'), (15, 'Baileys'), (16, 'Campari'), (17, 'Chambord'), (18, 'Creme de anything'), (19, 'Drambuie'), (20, 'Fireball'), (21, 'Frangelico'), (22, 'Galliano'), (23, 'Goldschlager'), (24, 'Jagermeister'), (25, 'Kahlua'), (26, 'Limoncello'), (27, 'Maraschino'), (28, 'Midori'), (29, 'Ouzo'), (30, 'Patron XO Cafe'), (31, 'Pastis'), (32, 'Sambuca'), (33, 'Sloe Gin'), (34, 'Southern Comfort'), (35, 'St Germain'), (36, 'Tia Maria'), (37, 'Tripel Sec'), (38, 'Tuaca'), (38, 'Cola')], default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(verbose_name='date_created')),
                ('sale_price', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('actual_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('created_date', models.DateTimeField(verbose_name='date_created')),
                ('status', models.BooleanField(default=False)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_name', to='inventory.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Mocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('sale_price', models.FloatField()),
                ('created_date', models.DateTimeField(verbose_name='date_created')),
                ('status', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Shisha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rent_price', models.FloatField()),
                ('created_date', models.DateTimeField(verbose_name='date_created')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(verbose_name='date_created')),
                ('status', models.BooleanField(default=False)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink', to='inventory.drink')),
            ],
        ),
    ]
