# Generated by Django 3.2.7 on 2021-09-17 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='drinkinventory',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='mocktail',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='shisha',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
    ]
