# Generated by Django 3.2.7 on 2021-09-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210917_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drink_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantity in ml'),
        ),
    ]
