# Generated by Django 3.2.7 on 2021-09-17 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
    ]
