# Generated by Django 3.2.7 on 2021-09-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210917_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cocktail_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='drink_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='mocktail_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shisha_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
